language: erlang
otp_release:
  - 18.3
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0

cache:
  directories:
  - $HOME/.otp_plt

script: ./testall.sh
after_success: ./update-gh-pages.sh
env:
  global:
    secure: DK9/0HuIhm9WSTZVZ6Ns/rlZuFmMILyA2HYTnGe+zbONpF8WAvcmbbw1uIccvqY3GX5dgwsr1tSM5P7ElAFS94PJTfou8bOtre1VcErDwLeoSjZuPNV8en02922IWiJ/qpz+N72Ca6VUclveJd86Jqoq/uSct0WlJ13ZJQTnKrU0GaAE36kdBh6T5J0vCmTfnIOMW3E42uWoWAyBN+j9Oq5aH25ZXe0e1ljGzjC5OWR562iAdsr+qugtZouX8vRPWf6QJSG0CD5RnzVZNgwrizEFkHGoUTz4/zgyQzlw4Y3pILj+/nY2px8sgxjZ7M+jft0cE72NR2MikaovEm4o0eK0yhQdyh0Fzj4vVSSfMRIerej8XHrDy+k/EH50TtWSqeDekN7ZLTHJeQGUM4dSD33rEbzQoZreM2/3Eh33limY0/Czbh848AvgJAjpmFHM9vOOX/ay/FcS5SFjsoBDb1Xzv8oAcHxWSIxVPMwnYzIgE+iBztO5R5gFGSt2tVMf7u1pTVZze03Rh6asfok5x2LUuIyZIAFkvjb6MQs2GyRdccuHLc8eUgd+ZBHQcgxQzVhBTVUFvMPOOca24TP7huJtz+I8c79kRSvS85wxu6x+rlwhUnYRWeYK6ltRtOCEPJqdmuIs1EaKsQkpVMyyLAt2ciqrelQ+l/GPUc0dCA0=
